### ISSUE TITLE
Support for statistics XML version 2.2

### ISSUE THREAD

**Issue by alpha01** [jforman/pybindxml#16]
Hello,

Is it possible to add support for XML version 2.2?

Example stats file (2 views configured in named.conf):
https://gist.github.com/alpha01/c980a8ee02b2db60b66604103b40b5b1

CentOS 6.8
Python 2.6.6
bind-9.8.2-0.47.rc1.el6_8.2.x86_64
bind-utils-9.8.2-0.47.rc1.el6_8.2.x86_64
bind-libs-9.8.2-0.47.rc1.el6_8.2.x86_64

I'm currently getting the following error when calling BindXmlReader.get_stats()

`  File "/usr/lib/python2.6/site-packages/pybindxml/reader.py", line 68, in get_stats
    raise XmlError('Support must be added before being able to support newly-encountered XML version %s.' % self.xml_version)
pybindxml.reader.XmlError: 'Support must be added before being able to support newly-encountered XML version 2.2.`

**Comment by alpha01** [comment]
Closing, I just saw https://github.com/jforman/pybindxml/commit/bba5c1a5f04ecfb4f98000384adb4a74e80dc272
It's forking time.

**Comment by MinhKMA** [comment]
hello, how to fix it? thank you
