### ISSUE TITLE
lxml 3.7

### ISSUE THREAD

**Issue by crrlcx** [jforman/pybindxml#17]
Hello!
lxml 3.7 support required

**Comment by jforman** [comment]
Hi @carrolcox, sorry for the long delay, I was away from my infrastructure for a while. The DNS server I run, which I develop against, is only showing version 3.6. What BIND version are you running that presents 3.7? And could you attach the XML output [1] from it that I could try to code again?

Thanks,

[1]: $ curl htttp://dnsserver:8053 | xmllint --format - > foo.xml
